### ISSUE TITLE
Failure to create run summary using NONMEM 7.4

### ISSUE THREAD

**Issue by stephengreene** [UUPharmacometrics/xpose#88] opened 2018-02-01 19:22 UTC
Hello,

I have run the same model (IV 1-CMT) on NM v 7.3 and 7.4. The run summary can be created with v 7.3 but when using v 7.4 I get the following error: 

Failed to create run summary. Evaluation error: 'str_trunc' is not an exported object from 'namespace:stringr'.

Possible compatibility issue with v 7.4?

I'm attaching my output file for your review.
[run1.txt](https://github.com/UUPharmacometrics/xpose/files/1686851/run1.txt)

**Comment by guiastrennec** [comment] 2018-02-01 20:00
Hi,

Thank you for your post. I am not able to reproduce your error with my install. Could you please send me a copy of your `sessionInfo()`?

I am guessing you may have an old version of stringr that could be the cause.

**Comment by stephengreene** [comment] 2018-02-01 21:38
That was the issue. I was working under the assumption that the two versions of R were the same when in fact they were not. Thanks for your help!

**Comment by guiastrennec** [comment] 2018-02-01 22:07
Great glad I could help. I will close the issue then.

**Closed by guiastrennec** 2018-02-01 22:07 UTC
